schema = 1

[module]
name = "caddy-eg"
repository_root = "."
source_module = "../../../proxmox-ug/ct/caddy/source"

[placement]
node = "proxmox-eg"
container_id = 117
address = "192.168.188.203"
service_type = "caddy"
