schema = 1

[module]
name = "openwrt-og"
repository_root = "."
source_module = "../../../proxmox-ug/vms/openwrt-ug/source"

[placement]
node = "proxmox-og"
vm_id = 109
address = "192.168.188.144"
service_type = "openwrt"
